### ISSUE TITLE
default select is not working

### ISSUE THREAD

**Issue by roshan-shelar** [markokostovski/react-combo-select#6]
eg code 
<ComboSelect type="multiselect" data={this.state.data} value={this.state.data[1]}/>

**Comment by markokostovski** [comment]
@roshan-shelar, can you be more descriptive? They way for you to have default selection is to put proper value or text.

`let standardArray = ["JA007D", "JA008D", "JA009D", "JA010D"]; 
<ComboSelect data={standardArray} value={standardArray[2]}/>`

It will select 'JA008D' as a default one.. Also this is just a minor example, it can get complex if you want additional mapping
